workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_m2
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.easibank.app
      vars:
        BUNDLE_ID: "com.easibank.app"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.cocoapods
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Setting up code signing..."
          keychain initialize
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release -archivePath build/Runner.xcarchive archive
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/IPA
    artifacts:
      - ios/build/IPA/Runner.ipa
      - ios/build/Runner.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - vuikhai3@gmail.com
        notify:
          success: true
          failure: true 